name: Update README with ArgoCD Apps

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update README with ArgoCD app versions
        uses: ./argocd-app-version-action
        with:
          argocd_server: ${{ secrets.ARGOCD_SERVER }}
          argocd_token: ${{ secrets.ARGOCD_TOKEN }}

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with ArgoCD apps and versions"
          git push
        working-directory: ./argocd-app-version-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}